# Generated by Django 3.0.7 on 2020-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsdetail',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='inter_location',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='inter_marks',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='intercollege',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='school_location',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='seat_category',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='vsat_marks',
        ),
        migrations.RemoveField(
            model_name='studentsdetail',
            name='vsat_rank',
        ),
        migrations.AddField(
            model_name='studentsdetail',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentsdetail',
            name='gender',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentsdetail',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetail',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetail',
            name='Registration_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentsdetail',
            name='branch',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
