# Generated by Django 3.0.7 on 2020-06-17 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200617_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullstudentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsdetail')),
            ],
        ),
    ]
