# Generated by Django 3.0.7 on 2020-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofile_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_you',
            field=models.TextField(null=True),
        ),
    ]
