# Generated by Django 3.0.7 on 2020-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Unit', models.CharField(choices=[('U1', 'UNIT 1'), ('U2', 'UNIT 2'), ('U3', 'UNIT 3')], max_length=30, null=True)),
                ('Category', models.CharField(choices=[('br', 'Blowroom'), ('wc', 'Waste Collection '), ('crd', 'Carding'), ('cd', 'Comber & Drawing')], max_length=200, null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
    ]
